### ISSUE TITLE
Benötige Hilfe

### ISSUE THREAD

**Issue by pantanis007** [AgentP38/Proxxon-HomeAssistant#3]
Hi AgentP38,

kannst du mir bei der Enrichtung meiner Proxon-Heizung helfen? Bin in dieser Hinsicht leider ein ziemlich Newbie :( Gerne auch gegen Aufwandsentschädigung. Grüße!

**Comment by AgentP38** [comment]
Ja gern brauche eine Kommunikationsmöglichkeit

**Comment by pantanis007** [comment]
Schreib mir gerne eine E-Mail: 
Danke freut mich noch jemand zu finden, der dabei helfen kann :)

**Comment by AgentP38** [comment]
Habe dir eine Email mit meiner Handynummer geschickt ...
